# Generated by Django 5.1.3 on 2024-12-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('OrderPlaced', 'OrderPlaced'), ('OutForDelivery', 'OutForDelivery'), ('Shipped', 'Shipped')], default='OrderPlaced', max_length=100),
        ),
    ]
